const Sequelize = require('sequelize');

const sequelize = new Sequelize('database', 'user', 'password', {
	host: 'localhost',
	dialect: 'sqlite',
	logging: false,
	storage: 'database.sqlite',
});

const Characters = require('./models/Characters')(sequelize, Sequelize.DataTypes);

const force = process.argv.includes('--force') || process.argv.includes('-f');

sequelize.sync({ force }).then(async () => {
	const characters = await Characters.bulkCreate([{
		name: 'MARIO',
		code_name: 'mario',
		id: '01',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/mario/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/mario.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/mario/mark.svg'
	}, {
		name: 'DONKEY KONG',
		code_name: 'donkey_kong',
		id: '02',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/donkey_kong/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/donkey_kong.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/donkey_kong/mark.svg'
	}, {
		name: 'LINK',
		code_name: 'link',
		id: '03',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/link/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/link.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/link/mark.svg'
	}, {
		name: 'SAMUS',
		code_name: 'samus',
		id: '04',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/samus/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/samus.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/samus/mark.svg'
	}, {
		name: 'DARK SAMUS',
		code_name: 'dark_samus',
		id: '04ᵋ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/dark_samus/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/dark_samus.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/dark_samus/mark.svg'
	}, {
		name: 'YOSHI',
		code_name: 'yoshi',
		id: '05',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/yoshi/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/yoshi.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/yoshi/mark.svg'
	}, {
		name: 'KIRBY',
		code_name: 'kirby',
		id: '06',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/kirby/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/kirby.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/kirby/mark.svg'
	}, {
		name: 'FOX',
		code_name: 'fox',
		id: '07',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/fox/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/fox.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/fox/mark.svg'
	}, {
		name: 'PIKACHU',
		code_name: 'pikachu',
		id: '08',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/pikachu/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/pikachu.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/pikachu/mark.svg'
	}, {
		name: 'LUIGI',
		code_name: 'luigi',
		id: '09',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/luigi/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/luigi.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/luigi/mark.svg'
	}, {
		name: 'NESS',
		code_name: 'ness',
		id: '10',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/ness/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/ness.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/ness/mark.svg'
	}, {
		name: 'CAPTAIN FALCON',
		code_name: 'captain_falcon',
		id: '11',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/captain_falcon/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/captain_falcon.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/captain_falcon/mark.svg'
	}, {
		name: 'JIGGLYPUFF',
		code_name: 'jigglypuff',
		id: '12',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/jigglypuff/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/jigglypuff.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/jigglypuff/mark.svg'
	}, {
		name: 'PEACH',
		code_name: 'peach',
		id: '13',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/peach/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/peach.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/peach/mark.svg'
	}, {
		name: 'DAISY',
		code_name: 'daisy',
		id: '13ᵋ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/daisy/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/daisy.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/daisy/mark.svg'
	}, {
		name: 'BOWSER',
		code_name: 'bowser',
		id: '14',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/bowser/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/bowser.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/bowser/mark.svg'
	}, {
		name: 'ICE CLIMBERS',
		code_name: 'ice_climbers',
		id: '15',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/ice_climbers/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/ice_climbers.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/ice_climbers/mark.svg'
	}, {
		name: 'SHEIK',
		code_name: 'sheik',
		id: '16',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/sheik/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/sheik.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/sheik/mark.svg'
	}, {
		name: 'ZELDA',
		code_name: 'zelda',
		id: '17',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/zelda/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/zelda.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/zelda/mark.svg'
	}, {
		name: 'DR. MARIO',
		code_name: 'dr_mario',
		id: '18',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/dr_mario/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/dr_mario.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/dr_mario/mark.svg'
	}, {
		name: 'PICHU',
		code_name: 'pichu',
		id: '19',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/pichu/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/pichu.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/pichu/mark.svg'
	}, {
		name: 'FALCO',
		code_name: 'falco',
		id: '20',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/falco/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/falco.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/falco/mark.svg'
	}, {
		name: 'MARTH',
		code_name: 'marth',
		id: '21',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/marth/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/marth.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/marth/mark.svg'
	}, {
		name: 'LUCINA',
		code_name: 'lucina',
		id: '21ᵋ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/lucina/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/lucina.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/lucina/mark.svg'
	}, {
		name: 'YOUNG LINK',
		code_name: 'young_link',
		id: '22',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/young_link/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/young_link.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/young_link/mark.svg'
	}, {
		name: 'GANONDORF',
		code_name: 'ganondorf',
		id: '23',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/ganondorf/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/ganondorf.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/ganondorf/mark.svg'
	}, {
		name: 'MEWTWO',
		code_name: 'mewtwo',
		id: '24',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/mewtwo/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/mewtwo.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/mewtwo/mark.svg'
	}, {
		name: 'ROY',
		code_name: 'roy',
		id: '25',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/roy/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/roy.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/roy/mark.svg'
	}, {
		name: 'CHROM',
		code_name: 'chrom',
		id: '25ᵋ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/chrom/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/chrom.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/chrom/mark.svg'
	}, {
		name: 'MR. GAME & WATCH',
		code_name: 'mr_game_and_watch',
		id: '26',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/mr_game_and_watch.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/mark.svg'
	}, {
		name: 'META KNIGHT',
		code_name: 'meta_knight',
		id: '27',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/meta_knight/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/meta_knight.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/meta_knight/mark.svg'
	}, {
		name: 'PIT',
		code_name: 'pit',
		id: '28',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/pit/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/pit.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/pit/mark.svg'
	}, {
		name: 'DARK PIT',
		code_name: 'dark_pit',
		id: '28ᵋ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/dark_pit/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/dark_pit.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/dark_pit/mark.svg'
	}, {
		name: 'ZERO SUIT SAMUS',
		code_name: 'zero_suit_samus',
		id: '29',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/zero_suit_samus/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/zero_suit_samus.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/zero_suit_samus/mark.svg'
	}, {
		name: 'WARIO',
		code_name: 'wario',
		id: '30',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/wario/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/wario.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/wario/mark.svg'
	}, {
		name: 'SNAKE',
		code_name: 'snake',
		id: '31',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/snake/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/snake.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/snake/mark.svg'
	}, {
		name: 'IKE',
		code_name: 'ike',
		id: '32',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/ike/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/ike.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/ike/mark.svg'
	}, {
		name: 'POKÉMON \nTRAINER',
		code_name: 'pokemon_trainer',
		id: '33/35',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/pokemon_trainer/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/pokemon_trainer.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/pokemon_trainer/mark.svg'
	}, {
		name: 'DIDDY KONG',
		code_name: 'diddy_kong',
		id: '36',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/diddy_kong/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/diddy_kong.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/diddy_kong/mark.svg'
	}, {
		name: 'LUCAS',
		code_name: 'lucas',
		id: '37',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/lucas/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/lucas.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/lucas/mark.svg'
	}, {
		name: 'SONIC',
		code_name: 'sonic',
		id: '38',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/sonic/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/sonic.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/sonic/mark.svg'
	}, {
		name: 'KING DEDEDE',
		code_name: 'king_dedede',
		id: '39',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/king_dedede/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/king_dedede.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/king_dedede/mark.svg'
	}, {
		name: 'OLIMAR',
		code_name: 'olimar',
		id: '40',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/olimar/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/olimar.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/olimar/mark.svg'
	}, {
		name: 'LUCARIO',
		code_name: 'lucario',
		id: '41',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/lucario/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/lucario.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/lucario/mark.svg'
	}, {
		name: 'R.O.B.',
		code_name: 'rob',
		id: '42',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/rob/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/rob.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/rob/mark.svg'
	}, {
		name: 'TOON LINK',
		code_name: 'toon_link',
		id: '43',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/toon_link/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/toon_link.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/toon_link/mark.svg'
	}, {
		name: 'WOLF',
		code_name: 'wolf',
		id: '44',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/wolf/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/wolf.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/wolf/mark.svg'
	}, {
		name: 'VILLAGER',
		code_name: 'villager',
		id: '45',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/villager/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/villager.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/villager/mark.svg'
	}, {
		name: 'MEGA MAN',
		code_name: 'mega_man',
		id: '46',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/mega_man/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/mega_man.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/mega_man/mark.svg'
	}, {
		name: 'Wii Fit TRAINER',
		code_name: 'wii_fit_trainer',
		id: '47',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/wii_fit_trainer/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/wii_fit_trainer.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/wii_fit_trainer/mark.svg'
	}, {
		name: 'ROSALINA & LUMA',
		code_name: 'rosalina_and_luma',
		id: '48',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/rosalina_and_luma/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/rosalina_and_luma.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/rosalina_and_luma/mark.svg'
	}, {
		name: 'LITTLE MAC',
		code_name: 'little_mac',
		id: '49',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/little_mac/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/little_mac.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/little_mac/mark.svg'
	}, {
		name: 'GRENINJA',
		code_name: 'greninja',
		id: '50',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/greninja/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/greninja.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/greninja/mark.svg'
	}, {
		name: 'Mii FIGHTER',
		code_name: 'mii_fighter',
		id: '51\n53  ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/mii_fighter/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/mii_fighter.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/mii_fighter/mark.svg'
	}, {
		name: 'PALUTENA',
		code_name: 'palutena',
		id: '54',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/palutena/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/palutena.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/palutena/mark.svg'
	}, {
		name: 'PAC-MAN',
		code_name: 'pac_man',
		id: '55',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/pac_man/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/pac_man.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/pac_man/mark.svg'
	}, {
		name: 'ROBIN',
		code_name: 'robin',
		id: '56',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/robin/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/robin.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/robin/mark.svg'
	}, {
		name: 'SHULK',
		code_name: 'shulk',
		id: '57',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/shulk/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/shulk.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/shulk/mark.svg'
	}, {
		name: 'BOWSER JR.',
		code_name: 'bowser_jr',
		id: '58',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/bowser_jr/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/bowser_jr.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/bowser_jr/mark.svg'
	}, {
		name: 'DUCK HUNT DUO',
		code_name: 'duck_hunt',
		id: '59',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/duck_hunt/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/duck_hunt.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/duck_hunt/mark.svg'
	}, {
		name: 'RYU',
		code_name: 'ryu',
		id: '60',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/ryu/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/ryu.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/ryu/mark.svg'
	}, {
		name: 'KEN',
		code_name: 'ken',
		id: '60ᵋ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/ken/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/ken.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/ken/mark.svg'
	}, {
		name: 'CLOUD',
		code_name: 'cloud',
		id: '61',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/cloud/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/cloud.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/cloud/mark.svg'
	}, {
		name: 'CORRIN',
		code_name: 'corrin',
		id: '62',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/corrin/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/corrin.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/corrin/mark.svg'
	}, {
		name: 'BAYONETTA',
		code_name: 'bayonetta',
		id: '63',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/bayonetta/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/bayonetta.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/bayonetta/mark.svg'
	}, {
		name: 'INKLING',
		code_name: 'inkling',
		id: '64',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/inkling/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/inkling.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/inkling/mark.svg'
	}, {
		name: 'RIDLEY',
		code_name: 'ridley',
		id: '65',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/ridley/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/ridley.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/ridley/mark.svg'
	}, {
		name: 'SIMON',
		code_name: 'simon',
		id: '66',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/simon/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/simon.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/simon/mark.svg'
	}, {
		name: 'RICHTER',
		code_name: 'richter',
		id: '66ᵋ',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/richter/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/richter.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/richter/mark.svg'
	}, {
		name: 'KING K. ROOL',
		code_name: 'king_k_rool',
		id: '67',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/king_k_rool/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/king_k_rool.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/king_k_rool/mark.svg'
	}, {
		name: 'ISABELLE',
		code_name: 'shizue',
		id: '68',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/shizue/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/shizue.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/shizue/mark.svg'
	}, {
		name: 'INCINEROAR',
		code_name: 'gaogaen',
		id: '69',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/gaogaen/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/gaogaen.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/gaogaen/mark.svg'
	}, {
		name: 'PIRANHA PLANT',
		code_name: 'packun_flower',
		id: '70',
		full: 'http://www.smashbros.com/assets_v2/img/fighter/packun_flower/main.png',
		thumb: 'http://www.smashbros.com/assets_v2/img/fighter/thumb_h/packun_flower.png',
		icon: 'http://www.smashbros.com/assets_v2/img/fighter/packun_flower/mark.svg'
	}]);
});